language: go

go:
    - "1.9"

branches:
  only:
    - /^development\/v.*$/
    - /^release\/v.*$/
    - /^v.*$/

install:
  - go get golang.org/x/crypto/pkcs12
  - go get github.com/pkg/errors
  - go get github.com/hashicorp/terraform
  - pushd $GOPATH/src/github.com/hashicorp/terraform
  - git checkout v0.11.4
  - popd

deploy:
  provider: releases
  file: terraform-provider-ddcloud.*.zip
  file_glob: true
  skip_cleanup: true
  on:
    repo: DimensionDataResearch/dd-cloud-compute-terraform
    branches:
      only:
        - /^release\/v.*$/
  api_key:
    secure: LTJjqC/G2arlaXfH+BGaU4dWUdBk9f6nKQwM0B3MtRZm76Lhi/wZFWOqzU3qSXbSGEHuSgfH4MsSM3AqQrLwsYRxkDo2QmwC05WrCa8ErdHPl0MWxEr1ZnRSysZsh2/BoVka1NsH93quPxCi6VjlSXPEjMAOtpMytsax3ac/gSZNOHrByEyxmNPFYlsS8eY+7B8D5c8EbBYZ6uuyN5vBqs46HwiAiXqIKEoUnjUjTrr/oyyH9Dd9RW98Ak6QF8ZnyrW1W6g4jyGPlRKfP6mhNI18jhn26w45sx6B84zKNY6YgmGwtrGJHfWC8qS0WBEDIKlmkRL8/j9mEzvsHMQ8wVYItgSPHl+kRnQjEuqI6vkiyEeFdmUrs1ZFKWbfkfO9Doz6pohQBxrATM480nEumnyRyeo50wxiXwe0BAlG5do/duqPT/p03sb2Zh8JolXqfbHcCXFdFiX9cEUBhaO+ofiWfpq0T2ezxr5fH8m+1TMZLOPhJc1yDXirnoEFtrm4QBYAfMJOeJhKHB12MZjMIirYahNoFT1+wDeTx/GGwfIkm4AG+OnYic2muRqIU+dG3DPpbn2YbkNTnS+nvdE73g8wcQQnjbsPaD7obuKnMrK7EDIgBl8CJwzdRan9kRc6BUuGzdGEJ1ern7yZKzIrmTz76hbPTRB6tTWTQh1uBb0=
