dist: trusty
sudo: required
language: go
services:
- docker
go:
- 1.12.x
env:
- GOMAXPROCS=4 GO111MODULE=on
install:
- go get golang.org/x/crypto/pkcs12
- go get github.com/pkg/errors
- go get github.com/hashicorp/terraform@v0.12.19
- go mod tidy
- go mod vendor
script:
- make dist
before_deploy:
- export TRAVIS_TAG="v3.0.5"
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: cVYCBCoBCRe+d+93Q1wjKt2UJNH8skjOPD0BQBshKBcTeq4XWI+VN1lFVKmkNvB3ZAC+jcA4WKOZWsyeHAgXgmdfw4L2bVIt+kNMq2BC9lSV2+eLwbF81SKqKme+plVqR+DcbvF5SPGUqP83pwGyKBPo+kxUV44ICnn4ZblaRngERg7mfmgRuKczjf1/P5FwTJYZnu4Kmof+ZCEWucpDsq+Ro7gCXlcyw3/+JypcoXzMHFvtSkPxpg+5YrBTtipQUfo6ZTyHsB155asPY60KOdwYGY+nZdlePbLM9KQqC6aH+VLnrZ5dM/CTD7BlJEjkaBS/KR/x0vuETvfDLgtTLfhyug7FrgOuBsIjiuRNmBWvPvQkKGB4VwDiABHW4ZDsz5XOpTrHI2wG4veI4RCoYdA7R8a7yPDYEDdYidN+Nfvl73z+57p/DbKMVVy/jMtstoYCd683jOgAkAAlCI33cVGJETNd7K77HrmH/8epFDcHXsHajP3j/pPIJxZtsUXohVVuluNoEpHPrSCAcEC/GaXmCkuUcm8vGzow/knsUeAHJ1ikKWF25LCtUa73fGFBTOVGBkvwVvofaxMay0S4ypKPdqYrw4XgChKAsIIWjQlRj7o0ojmzWFeeghipeZRznAfKkIaxEZnF61pj51O1E9ePenlW8A15v/8mtMm1NgU=
  file: _bin/
  on:
    repo: DimensionDataResearch/dd-cloud-compute-terraform
    branch: release/v12.0
  skip_cleanup: 'true'
